# Generated by Django 5.0.6 on 2024-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0002_referenceamount_remove_student_has_access_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_period',
            field=models.CharField(choices=[('normal', 'Normal'), ('type_b', 'Type B'), ('type_c', 'Type C'), ('type_d', 'Type D')], default='normal', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='referenceamount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
