# Generated by Django 5.0.6 on 2024-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0003_student_entry_period_alter_referenceamount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceamount',
            name='entry_period',
            field=models.CharField(default='normal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referenceamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
