# Generated by Django 5.0.6 on 2024-06-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0004_referenceamount_entry_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='derogation_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
