# Generated by Django 5.0.6 on 2024-06-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('category1', 'Not authorised while i have paid'), ('category2', 'Derogation: Not ready financially'), ('category3', 'Exam done but status failed'), ('category4', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
