# Generated by Django 5.0.6 on 2024-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0008_remove_message_receiver_message_receivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='backgrounda.jpg', null=True, upload_to='static/images/profile_pictures/'),
        ),
    ]
