# Generated by Django 5.0.6 on 2024-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='background.jpg', null=True, upload_to='static/images/profile_pictures/'),
        ),
    ]
