# Generated by Django 5.0.6 on 2024-06-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('type_exam', models.CharField(choices=[('CAT2', 'CAT2'), ('FAT', 'FAT'), ('SPECIAL', 'SPECIAL'), ('ToBeDetermined', 'To be determined')], max_length=20)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_user.level')),
            ],
        ),
    ]
