# Generated by Django 5.0.6 on 2024-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_admins', '0002_examstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatus',
            name='entry_time',
            field=models.DateTimeField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='examstatus',
            name='exit_time',
            field=models.DateTimeField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='examstatus',
            name='status',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
